<<<<<<< HEAD
#dotnet build pipeline
=======
>>>>>>> 6c432a67c399dd211494d7e7e5f851539fffa916
trigger:
    - '*'

pool:
<<<<<<< HEAD
    vmImage: ubuntu-20.04
=======
    vmImage: 'ubuntu-20.04'
>>>>>>> 6c432a67c399dd211494d7e7e5f851539fffa916
    demands:
        - npm

variables:
    buildConfiguration: 'Release'
    wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
    dotnetSdkVersion: '6.x'

steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
<<<<<<< HEAD
          packageType: sdk
=======
>>>>>>> 6c432a67c399dd211494d7e7e5f851539fffa916
          version: '$(dotnetSdkVersion)'

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
          verbose: false

    - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
      displayName: 'Compile Sass assets'

    - task: gulp@1
      displayName: 'Run gulp tasks'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
          command: 'restore'
          projects: '**/*.csproj'

    - template: templates/build.yml
      parameters:
          buildConfiguration: 'Debug'

    - template: templates/build.yml
      parameters:
          buildConfiguration: 'Release'

    - task: PublishPipelineArtifact@1
      inputs:
          TargetPath: '$(Pipeline.Workspace)'
          artifactType: 'pipeline'
          artifactName: 'drop'
      displayName: 'Publish Artifact: drop'
      condition: succeeded()
